version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/scottleedavis/mattermost-plugin-ascii-plot
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v -coverprofile=server/coverage.txt ./...
      #- run: make test
      - codecov/upload:
          file: server/coverage.txt
