// This file is automatically generated. Do not modify it manually.

package main

var manifest = struct {
	ID      string
	Version string
}{
	ID:      "com.github.scottleedavis.mattermost-plugin-plot-post",
	Version: "0.1.0",
}
